# Generated by Django 5.1.5 on 2025-01-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('sender_mail', models.EmailField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('footer', models.TextField()),
                ('button', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('objet', models.CharField(max_length=255)),
                ('mail_body', models.TextField()),
                ('reponse', models.BooleanField()),
                ('explication', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbre_questions', models.IntegerField()),
                ('nbCorrect', models.IntegerField()),
                ('nbFausse', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.user')),
            ],
        ),
    ]
